# Generated by Django 4.2 on 2024-04-25 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweetApp', '0004_tweetmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Beğenme Sayısı')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweetApp.tweetmodel', verbose_name='Tweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Beğenen Kişi')),
            ],
        ),
    ]
